apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-200305-g6r8-service
spec:
  selector:
    app: enterprise-system-200305-g6r8
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
